### ISSUE TITLE
make postgres.rtf一直卡主不动

### ISSUE THREAD

**Issue by qq363960630** [postgres-cn/pgdoc-cn#108]
make postgres.rtf一直卡主不动，试了很多次，每次至少有半小时，请问哪里可以看到类似日志的东西啊，我不知道这个问题是怎么发生的，又应该怎么解决呢

**Comment by ChenHuajun** [comment]
这个文档的编译时间比较长，可能是正常的。日志就是控制台的输出，你可以make postgres.rtf -n 看下执行的什么命令然后手动执行。

**Comment by ChenHuajun** [comment]
无进一步反馈，先关闭

**Comment by ChenHuajun** [comment]
无进一步反馈，先关闭
