### ISSUE TITLE
" gmake: command not found"

### ISSUE THREAD

**Issue by luckypoem** [postgres-cn/pgdoc-cn#114]
hi.

root@localhost:~/pgdoc-cn-site/postgresql-9.3.1/doc/src/sgml# gmake html
-bash: gmake: command not found
root@localhost:~/pgdoc-cn-site/postgresql-9.3.1/doc/src/sgml#

gmake是个什么命令？如何解决？

**Comment by zjin1126** [comment]
gmake就是GNU make。
大部分平台上指令是make，改用make试试。
