### ISSUE TITLE
翻译不准确

### ISSUE THREAD

**Issue by taojin0505** [postgres-cn/pgdoc-cn#115]
http://postgres.cn/docs/9.4/datatype-textsearch.html
位置：
8.11. 文本搜索类型

tsquery类型用于代表查询
这句的原文是
the tsquery type similarly represents a text query.
和翻译意思有些差别

**Comment by ChenHuajun** [comment]
意思差不多啊？

**Comment by rim99** [comment]
应该是：“tsquery类型类似于text文本查询”

**Comment by ChenHuajun** [comment]
参考9.6的翻译，改成"tsquery类型表示一个文本查询"
