### ISSUE TITLE
9.5以后版本INSERT命令说明缺少UPSERT部分

### ISSUE THREAD

**Issue by stoneqduc** [postgres-cn/pgdoc-cn#126]
首先感谢大家的无私奉献。
发现一个小问题，9.5的新功能UPSERT在中文帮助文档里没有反映。

-- 中文版INSERT，还是9.4的版本的内容构成
http://www.postgres.cn/docs/9.5/sql-insert.html

-- 官方说明，已经实现UPSERT功能了
https://www.postgresql.org/docs/9.5/static/sql-insert.html
"where conflict_target can be one of:..." 部分是 UPSER部分的功能描述，望追加

**Comment by ChenHuajun** [comment]
这个页面还没有翻译，沿用是9.4的。凡是下面的wiki里未翻译的页面都是9.4的内容。   https://github.com/postgres-cn/pgdoc-cn/wiki/pg9.5
