### ISSUE TITLE
阅读过程中发现的翻译小错误-HPJ

### ISSUE THREAD

**Issue by hepengju** [postgres-cn/pgdoc-cn#151]
非常感谢此项目组成员的努力与辛苦,才得以看到中文版本的帮助手册文件.
在查看的过程中, 对于已经发现的几处小错误进行了记录, 以便使得手册文件更加准确. 

时间: 2017/07/23
作者: 何鹏举    
文件: PostgreSQL9.6.0-CN-v1.0.pdf
阅读: P1 -> P550

**简要叙述如下,详细见附件word文档:** 
P63: 逐渐 -> 主键
P101: 先忽略吗? 实测先OFFSET,再LIMIT的
P264: 返回空值
P280: 客户端/服务器
P387: 访问多了一个
P484: 极其 -> 及其
P504: 哦都市 -> 都是, 此段中还有一段忘掉删除或注释的英文.
P531: 未翻译英文
P535: 空值 -> 控制

[PostgreSQL查看发现的小错记录_HPJ_20170723.docx](https://github.com/postgres-cn/pgdoc-cn/files/1167472/PostgreSQL._HPJ_20170723.docx)

**Comment by ChenHuajun** [comment]
非常感谢提供反馈! 我们会尽快修改

**Comment by ChenHuajun** [comment]
@zuyue  http://www.postgres.cn/docs/9.6/default-roles.html 没有翻译，请翻译一下。

**Comment by ChenHuajun** [comment]
fixed
