### ISSUE TITLE
本页面与英文原文不符

### ISSUE THREAD

**Issue by zuyue** [postgres-cn/pgdoc-cn#153]
内容与英文不一致

**Comment by ChenHuajun** [comment]
哪个页面？

**Comment by zuyue** [comment]
经过检查，发现是PG新修改的内容，不是翻译时的问题，是pg_user_mappings 章节（提交问题的时候竟然不定位我所在的html页面，这个我是真的不知道，真不是故意的）

**Comment by ChenHuajun** [comment]
最新的英文版PostgreSQL 9.6.4的 50.82. pg_user_mappings 比9.6.0有一些修改。中文手册是基于9.6.0的，因此不是问题。
