### ISSUE TITLE
一个简单的 typo, 请修改.

### ISSUE THREAD

**Issue by nankingrider** [postgres-cn/pgdoc-cn#159]
http://postgres.cn/docs/9.6/sql-copy.html
文本格式

在使用text格式时，读取或写入的是一个文本文件， 其中每一行就是表中的一行。一行中的列被定界字符分隔。列值 本身是由输出函数产生的或者是可被输入函数接受的属于每个属性 数据类型的字符串。在为空值的列的位置使用指定的空值串。如果 输入文件的任何行包含比预期更多或者更少的列， COPY FROM将会抛出一个错误。如 果指定了OIDS，在处理用户数据列<**志气啊**>， 会从第一列读取 OID 或者把 OID 写入第一列。

其中应该是 **之前**

因为公司网络问题没法自己修改, 就提个issue了.

**Comment by ChenHuajun** [comment]
已fix，多谢反馈！
