### ISSUE TITLE
我觉得翻译的文档结构组织有些问题

### ISSUE THREAD

**Issue by tannineo** [postgres-cn/pgdoc-cn#164]
文档结构使得查找变更困难.  
1. 英文原版的注释掺杂在翻译文稿中 体验不好.  
按wiki, 现在我们如果尝试翻译, 需要下载wiki中提供的源码, 人工比对:  
  - 源码中doc下sgml文件  
  - pgdoc-cn的sgml文件  
事实是pgdoc-cn的sgml文件包含着中文翻译的同时也保留着英文原文的注释, 这样diff的体验不好.  
但不包含英文原文又会使得pull request之后的审阅变得困难, 因为这样会不知道这次pull request变更的英文原文, 使得审阅翻译困难.  

2. 增加翻译起点版本和目标版本的tag  
我们都在使用git, 包括postgres, 所以我们应该指明这一版本翻译基于哪个release tag, 包括上一版本是基于哪个tag. 有了这两个tag, 我们可以比对前后的文档改动, 甚至包括postgres源代码上的改动.  
这方便在postgres官方repo上diff查看变更, 也利于翻译(假如翻译过程中需要查看源代码帮助理解).  

我的方案是:
1. 从翻译的sgml文件中删去英文原文注释.  
2. 工程中加入英文sgml文件夹, 是翻译起点的sgml(如我们翻译10.1, 一开始英文sgml是9.6), 保留上一个版本的sgml方便与新的英文sgml进行diff, 找到变更点.  
3. 每次翻译一个文件时 同时更新英文sgml和中文sgml, 这样每个commit和pull request中改动一目了然.
4. 保留新版源码包`tar.gz`的下载地址.

这样还有一个好处: postgres源码repo过于巨大(我挂vpn 100KB/s clone 了3h+ 虽然在clone时可以缩小范围), 翻译者通常只需要 clone pgdoc-cn 就可以了, 而且可以不用在意翻译的起点对应的是哪个tag. 而且可以比对新版源码包中的sgml和pgdoc-cn的源码包, 找到变更点.

**Comment by tannineo** [comment]
issue无关的问题:
http://www.postgres.cn/ 能开源么?
假如我想改善网站或者搞个新的?

**Comment by ChenHuajun** [comment]
关于英文原文注释的问题其实之前也有一些讨论，但是在缺少注释后审阅会很不便。即使把英文移到另一个目录下，放在同一个pr里提交。因为很多sgml的翻译点太多了，分在2个文件里就很难找到它们的关联，而且这个英文原文注释不仅用在review PR上，我们阅读在线手册时如果发现哪一处翻译的意思不是很明白，可以通过右上角的"纠错本页面"跳转到sgml，查看英文原文。

关于sgml文件的比对，可能每个人喜欢的工具和做法不同。比如我喜欢同时开两个winmerge窗口，一个winmerg比对10.1的英文原始sgml和9.6.0的原始英文sgml，找到变更位置(行号)；另一个winmerg比对pgdoc-cn的sgml文件和10.1的英文sgml，在对应的变更位置进行翻译, 由于pgdoc-cn的sgml文件中保留的英文注释，这些英文注释可以和10.1的英文sgml很好的对齐。

当然,如果你觉得这些英文注释碍事，影响翻译，也可以先用  tools/pgdoc_add_commet.py 这个工具把本地文档中的注释全部删掉， 翻完后再用这个工具把注释加回来。

文档的起点版本和目标版本，wiki上应该已经说明得很清楚了。

postgres-cn的源码repo过于巨大，我想主要原因应该是，sgml文件本身比较大，而且repo里保存了9.3.1以来所有版本的文档，这些历史版本都以分支的形式存在。

谢谢你提这么多不错的意见。这些问题也可以到我们的文档QQ群 309292849 进行讨论。

**Comment by tannineo** [comment]
了解了 有个9.6.0的tar包已经方便很多了 : )
