### ISSUE TITLE
www.postgres.cn 能开源么?

### ISSUE THREAD

**Issue by tannineo** [postgres-cn/pgdoc-cn#165]
放到github上来?
可以改善网站, 或者干脆搞个新的?
不好意思, 这个和pgdoc没啥关系哈...

**Comment by ChenHuajun** [comment]
你在PG社区的微信群里吗?  这些建议可以在群里反映啊 ：)

**Comment by 1c7** [comment]
借这个 issue 特意感谢一下翻译人员，正在读~，非常有帮助
谢谢。

**Comment by ChenHuajun** [comment]
已开源，位置在 https://github.com/postgres-cn/website 。有好的建议欢迎提issue和pr
