### ISSUE TITLE
分区表部分

### ISSUE THREAD

**Issue by jiawangliu88** [postgres-cn/pgdoc-cn#182]
http://www.postgres.cn/docs/10/ddl-partitioning.html

分区表部分的改动相对比较大，希望能先把这部分翻译出来
非常感谢

**Comment by zuyue** [comment]
按照计划，这部分的翻译工作将在3月5号开始进行，没问题的话，下周这部分就和大家见面了。
另外，若翻译中有错误的地方，希望及时提出来，大家一起讨论，改进翻译质量。

**Comment by ChenHuajun** [comment]
已翻译完
