### ISSUE TITLE
xml tag中使用全角引用字符导致编译错误

### ISSUE THREAD

**Issue by ChenHuajun** [postgres-cn/pgdoc-cn#183]
## 现象

build.log中有如下错误
... 
python pgdoc_code_mask.py -r postgres.xml
开始恢复"postgres.xml"中被转义的中文字符...
postgres.xml
Traceback (most recent call last):
  File "pgdoc_code_mask.py", line 126, in <module>
    process(sourceFile,code_unmask)
  File "pgdoc_code_mask.py", line 98, in process
    process_file(source,code_unmask)
  File "pgdoc_code_mask.py", line 69, in process_file
    fout.write(masktext)
  File "/usr/lib64/python2.6/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib64/python2.6/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
  File "/usr/lib64/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: invalid continuation byte
make[2]: *** [postgres.xml] Error 1
make[2]: *** Deleting file `postgres.xml'
make[2]: Leaving directory `/home/pgdoc/gitrep/postgresql-10/doc/src/sgml'
make[1]: *** [html] Error 2
make[1]: Leaving directory `/home/pgdoc/gitrep/postgresql-10/doc/src'
make: *** [html] Error 2
make html failed!

## 原因

xml tag中使用了全角引用字符
ref/create_publication.sgml:
```
请参见<xref linkend =“logical-replication-publication”>。
```

`python pgdoc_code_mask.py .`转义后变成下面的形式
```
<xref linkend =$${4oCc}logical-replication-publication$${4oCd}>
```

`/usr/bin/osx`处理后，又变成以下形式。
```
<xref linkend=”$${4occ}logical-replication-publication$${4ocd}“>
```

$${4oCc}转成小写$${4occ}，导致后面解除转义失败。

**Comment by zuyue** [comment]
已修改

**Comment by ChenHuajun** [comment]
有问题的是下面几处
```
[pgdoc@i-yh5e8qjy sgml]$ grep '=“' *
release-10.sgml:	  新的系统视图<link linkend =“view-pg-sequences”><structname>pg_sequences</structname></link>
release-10.sgml:	  而不是内编译的默认值。请参阅<xref linkend =“guc-ssl-dh-params-file”>。
release-10.sgml:        添加<xref linkend =“guc-max-parallel-workers”>
release-10.sgml:         更改<xref linkend =“guc-log-line-prefix”>的默认值，使其包含当前时间戳
[pgdoc@i-yh5e8qjy sgml]$ grep '=“' ref/*
ref/create_publication.sgml:   请参见<xref linkend =“logical-replication-publication”>。
```
