### ISSUE TITLE
postgres.cn访问不了

### ISSUE THREAD

**Issue by klyun** [postgres-cn/pgdoc-cn#188]
首页还可以打开，但是内容打不开了，比如：http://www.postgres.cn/docs/9.3/sql-savepoint.html
提示如下：

该网站暂时无法访问

尊敬的用户，您好

很抱歉，该网站暂时无法访问，可能由以下原因导致：

原因一：未备案或未接入；根据《非经营性互联网信息服务备案管理办法》，网站需要完成备案或接入。

原因二：网站内容与备案信息不符或备案信息不准确；根据《非经营性互联网信息服务备案管理办法》，网站内容需要与备案信息一致，且备案信息需真实有效。建议网站管理员尽快修改网站信息。

备案管理平台点此进入 ，购买云服务器享30元/月超低价

**Comment by ChenHuajun** [comment]
问题正在处理。这期间临时可以通过IP访问
- http://123.57.214.158/docs/9.3  
- http://123.57.214.158/docs/9.3.4  
- http://123.57.214.158/docs/9.4  
- http://123.57.214.158/docs/9.5  
- http://123.57.214.158/docs/9.6  
- http://123.57.214.158/docs/10
