### ISSUE TITLE
21.6章节，少翻译了2句

### ISSUE THREAD

**Issue by zhuangxd** [postgres-cn/pgdoc-cn#202]
Functions, triggers and row-level security policies allow users to insert code into the backend server that other users might execute unintentionally. Hence, these mechanisms permit users to “Trojan
horse” others with relative ease. The strongest protection is tight control over who can define objects.
```
Where that is infeasible, write queries referring only to objects having trusted owners. Remove from
search_path the public schema and any other schemas that permit untrusted users to create objects.
```

**Comment by ChenHuajun** [comment]
这个翻译基于10.2，这2句是10.1 以后版本加的
