### ISSUE TITLE
5.8.3少翻译一段

### ISSUE THREAD

**Issue by zhuangxd** [postgres-cn/pgdoc-cn#203]
The ability to create like-named objects in different schemas complicates writing a query that references precisely the same objects every time. It also opens up the potential for users to change the behavior of other users' queries, maliciously or accidentally. Due to the prevalence of unqualified names
in queries and their use in PostgreSQL internals, adding a schema to search_path effectively trusts
all users having CREATE privilege on that schema. When you run an ordinary query, a malicious user
able to create objects in a schema of your search path can take control and execute arbitrary SQL
functions as though you executed them

**Comment by zuyue** [comment]
请问您看的是哪个版本的

**Comment by zhuangxd** [comment]
看错了 我看得是10.4
