### ISSUE TITLE
请问如何转换成epub格式？

### ISSUE THREAD

**Issue by sillydong** [postgres-cn/pgdoc-cn#204]
方便阅读，PDF格式搜索和阅读不方便，尤其在小屏上的时候

谢谢！

**Comment by floating-cat** [comment]
我从现在项目源代码里编译出了 epub 版（10.1 版），然后用 Calibre 版转出了 azw3 的版本，你可以下载附件。

大概的编译流程是这样子的：
1、参考官方 https://www.postgresql.org/docs/10/docguide-toolsets.html 下载你需要编译的版本的依赖。
2、下载对应的原版的源代码，然后将这个仓库下的 postgresql/doc/src/sgml 替换原版下的 doc/src/sgml。
3、在替换后的原版源代码下 `./configure`。
4、进入到 doc/src/sgml 下，把 Makefile 文件里的所有的 `--valid` 的文字删掉（因为现在该仓库下的中文版生成的 XML 有些语法不太对），然后 `make postgres.epub`。

[PostgreSQL 10.1 Shou Ce - PostgreSQL Quan Qiu Kai Fa Zu.epub.zip](https://github.com/postgres-cn/pgdoc-cn/files/2591490/PostgreSQL.10.1.Shou.Ce.-.PostgreSQL.Quan.Qiu.Kai.Fa.Zu.epub.zip)
[PostgreSQL 10.1 Shou Ce - PostgreSQL Quan Qiu Kai Fa Zu.azw3.zip](https://github.com/postgres-cn/pgdoc-cn/files/2591491/PostgreSQL.10.1.Shou.Ce.-.PostgreSQL.Quan.Qiu.Kai.Fa.Zu.azw3.zip)
