### ISSUE TITLE
事务一节,开启事务用begin?

### ISSUE THREAD

**Issue by phpstudyer** [postgres-cn/pgdoc-cn#222]
BEGIN;
UPDATE accounts SET balance = balance - 100.00
    WHERE name = 'Alice';
-- 等等
COMMIT;

这是怕是该:
START TRANSACTION;
UPDATE accounts SET balance = balance - 100.00
    WHERE name = 'Alice';
-- 等等
COMMIT;

**Comment by ChenHuajun** [comment]
https://www.postgresql.org/docs/10/sql-begin.html
