### ISSUE TITLE
SQL 命令CREATE POLICY翻译不完全

### ISSUE THREAD

**Issue by sunshinerxu** [postgres-cn/pgdoc-cn#263]
在PART VI. 的参考中，SQL 命令**CREATE POLICY**的翻译没有全部完成， 在针对每种命令的策略UPDATE之后的大部分内容没有完全翻译，包括表240 Policies Applied by Command Type 表格也没有翻译。

对应的XML文件为ref/create_policy.sgml，自576行开始，至1045行。

**Comment by ChenHuajun** [comment]
@sunshinerxu 能不能加下我微信chenhj_07

**Comment by sunshinerxu** [comment]
已经合并至master。
