### ISSUE TITLE
Found typos from document

### ISSUE THREAD

**Issue by GangLiCN** [postgres-cn/pgdoc-cn#275]
I found some typos from below URL:
   http://www.postgres.cn/docs/11/catalog-pg-collation.html

Wrong text:
注意在这个目录中的唯一键是（collname、 collencoding、 collencoding）， 不仅仅是（collname，collencoding）

Correct text should be:
注意在这个目录中的唯一键是（collname、 collnamespace、 collencoding）， 不仅仅是（collname，collnamespace）

Note that above typos only exist in PG11 doc,  In PG10 doc, the translation is correct !

**Comment by ChenHuajun** [comment]
非常感谢报告错误！
