### ISSUE TITLE
样式不一致

### ISSUE THREAD

**Issue by jingsam** [postgres-cn/pgdoc-cn#301]
语法模块在间距、加粗等方面不一致

![image](https://user-images.githubusercontent.com/1522494/90326309-8a45de80-dfb9-11ea-91d0-2491978584bc.png)

**Comment by ChenHuajun** [comment]
收到，现在看不到图，回头我看下。

**Comment by ChenHuajun** [comment]
postgresql.org官网的css和PG源码中的css不一样，所以显示风格有差异。
这处的加粗已更新到中文文档的css中。
