### ISSUE TITLE
翻译质量相当高.

### ISSUE THREAD

**Issue by goodgoodwish** [postgres-cn/pgdoc-cn#317]
作为 25 年的数据库工程师, 读过以后, 觉得这份文档翻译的质量相当高. 必须夸赞.

请问有没有 kindle 格式的离线文档下载? 比如 mobi 等等.

**Comment by ChenHuajun** [comment]
离线手册下载 中有epub格式的文档，你看是不是可以用
https://github.com/postgres-cn/pgdoc-cn/releases/tag/v12.2-1.0

**Comment by goodgoodwish** [comment]
> 离线手册下载 中有epub格式的文档，你看是不是可以用
> https://github.com/postgres-cn/pgdoc-cn/releases/tag/v12.2-1.0

谢谢啦. 对. 我用 Calibre 把 epub 转换成了  mobi. 效果不错.

就是百度网盘在国外登录不方便, 需要电话号码等等. 哈哈哈.
