### ISSUE TITLE
在pg12 使用fo2pdf 生成的pdf中文是乱码的 中文都是显示#####

### ISSUE THREAD

**Issue by yanghuantian** [postgres-cn/pgdoc-cn#333]

**Comment by yanghuantian** [comment]
请问这个如何解决啊？

**Comment by ChenHuajun** [comment]
https://github.com/postgres-cn/pgdoc-cn/wiki/PostgreSQL%E7%A6%BB%E7%BA%BF%E6%89%8B%E5%86%8C%E5%8F%91%E5%B8%83%E6%AD%A5%E9%AA%A4

参考wiki这个页面
