### ISSUE TITLE
epub 格式13.1文档在厚墨APP中代码不换行

### ISSUE THREAD

**Issue by l1t1** [postgres-cn/pgdoc-cn#354]
![Screenshot_20210801_175117_cn deepink reader](https://user-images.githubusercontent.com/23301704/127768006-43f7835d-eaee-4708-b269-513333a683cb.jpg)
pdf没问题

**Comment by ChenHuajun** [comment]
建议换个app。 亲测neat reader显示正常。
另外你可以给这个APP反馈一个BUG。PG手册里代码用<pre>标签表示，这个APP没有正确处理<pre>标签。
