### ISSUE TITLE
关于Pg9.5.3手册打包成pdf的问题

### ISSUE THREAD

**Issue by killerwzb** [postgres-cn/pgdoc-cn#362]
您好：
      我这边按照说明配置好了以后，可以打包成html或者postgres-A4.tex-pdf，但是直接打包成pdf文件就报错，请问还需要什么处理步骤吗，有没有具体说明，谢谢。

**Comment by ChenHuajun** [comment]
参考 https://github.com/ChenHuajun/blog_xqhx/blob/main/2014/2014-10-01-%E5%88%A9%E7%94%A8openjade%2Bctex%2Bjadetex%E4%BB%8Esgml%E7%94%9F%E6%88%90PostgreSQL%E4%B8%AD%E6%96%87pdf%E6%89%8B%E5%86%8C.md
