### ISSUE TITLE
PostgreSQL插入数据时

### ISSUE THREAD

**Issue by Zjn2Lhy** [postgres-cn/pgdoc-cn#364]
PostgreSQL插入数据时,报错 ERROR:  no partition of relation "mk_pg_line" found for row  (exec4 10.92.190.22:3800 pid=34454)
DETAIL:  Partition key of the failing row contains (province_code) = (null).

**Comment by ChenHuajun** [comment]
没有和插入行匹配的分区，参考下面的注释。

```
		/*
		 * If this partitioned table has no partitions or no partition for
		 * these values, error out.
		 */
```

**Comment by Zjn2Lhy** [comment]
你好，邮件已收到，我会尽快回复你的，谢谢。
