### ISSUE TITLE
读取HDFS文件,写入到postgreSQL上的(有分区)表,一直在写入,但是数据一直没写进去,也没报错

### ISSUE THREAD

**Issue by Zjn2Lhy** [postgres-cn/pgdoc-cn#365]
读取HDFS文件,写入到postgreSQL上的(有分区)表,一直在写入,但是数据一直没写进去,也没报错,后面分区字段时,我给了个固定分区,也是写不进去,也没报错,程序一直在跑

**Comment by ChenHuajun** [comment]
确认有分区创建是否正常，和上一个问题是否同一问题
