### ISSUE TITLE
PostgreSQL 12 手册翻译错误

### ISSUE THREAD

**Issue by Spike1337** [postgres-cn/pgdoc-cn#373]
- 27.2.统计收集器章节中 pg_stat_wal_receiver视图 翻译笔误：)

![pic_20220301104830](https://user-images.githubusercontent.com/77609415/156095531-e498ea4e-7179-4432-a91e-ca187261cc08.png)
![pic_20220301104839](https://user-images.githubusercontent.com/77609415/156095537-e448aac7-5293-4282-9d05-69ab522d55d3.png)

**Comment by ChenHuajun** [comment]
已修复，多谢
