### ISSUE TITLE
出现多余的文字

### ISSUE THREAD

**Issue by lixiang4u** [postgres-cn/pgdoc-cn#376]
页：http://www.postgres.cn/docs/14/ddl-partitioning.html
行：没有自动的方法**啊**验证所有的CHECK约束之间是否互斥。
多了个【啊】字

页：http://www.postgres.cn/docs/14/ddl-partitioning.html
行：最重要的设计决策之一是列或者**如和**对数据进行分区的。
【和】应该为【如何】？

**Comment by ChenHuajun** [comment]
fixed
