### ISSUE TITLE
翻译有误

### ISSUE THREAD

**Issue by wqyvalinor** [postgres-cn/pgdoc-cn#379]
pg13.1翻译版

4.1.2. 常量
第一句 “显示” 应为 “显式” 

33.1. 数据库连接控制函数
“PQconnectStart后面跟着后面跟着PQconnectPoll”中"后面跟着"重复

37.1. 扩展性如何工作
第二段，"trivial"翻译为“繁琐”意思完全不对吧？应该是“把用SQL编写的代码加入到服务器更加轻而易举”？

**Comment by ChenHuajun** [comment]
fixed
