### ISSUE TITLE
参考部分，PostgreSQL 服务器应用中pg_upgrade命令的描述部分，表述有问题

### ISSUE THREAD

**Issue by wlf123a** [postgres-cn/pgdoc-cn#382]
参考部分，PostgreSQL 服务器应用中pg_upgrade命令的描述部分，表述有问题：
描述部分第二段最后一句：
 如果一个未来的主发行没有把数据存储格式改得让旧数据格式不可读取，这类 升级就用不上pg_upgrade（社区将尝试避免这类情况）。
是否应该是：
如果一个未来的主发行把数据存储格式改得让旧数据格式不可读取，这类 升级就用不上pg_upgrade（社区将尝试避免这类情况）。
这样表述是否更佳：
如果未来的主要版本更改了数据存储格式，导致旧数据格式不可读，那么 pg_upgrade 将无法用于此类升级。

**Comment by ChenHuajun** [comment]
fixed
