### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by lixiang4u** [postgres-cn/pgdoc-cn#383]
页：http://www.postgres.cn/docs/14/queries-with.html
行：一个非常简单的例子是计算从1到100的整数合的查询
整数【合】的查询，应该为：整数【和 】的查询 吧

页：http://www.postgres.cn/docs/14/queries-with.html
行：我们可以项这个有循环倾向的查询增加两个列path和cycle
我们可以【项】，应该为：我们可以【向】 吧

**Comment by YtxCash** [comment]
页：http://www.postgres.cn/docs/14/ddl-constraints.html#DDL-CONSTRAINTS-PRIMARY-KEYS
行：限制删除或者级联删除是两种最常见的选项。RESTRICT阻止删除一个被引用的行。NO ACTION表示在约束被检察时如果有任何引用行存在，

检察 -> 检查
