### ISSUE TITLE
PostgreSQL同样也提供了返回实时时间值的函数， 它们的返回值会在事务中随时间的前进而变化。这些不附合 SQL 标准的函数列表如下：

### ISSUE THREAD

**Issue by 18752125869** [postgres-cn/pgdoc-cn#392]
这下面不应该包含 now(), now()返回的是事务开始的时间

**Comment by ChenHuajun** [comment]
这里指非SQL标志函数列表，包含now（）。 但是上面的翻译也确实和英文意思有出入。 
已改为：`PostgreSQL还提供了返回当前语句的开始时间以及调用该函数时的实际当前时间的函数`
