### ISSUE TITLE
37.2.5 翻译有误

### ISSUE THREAD

**Issue by Fatal01** [postgres-cn/pgdoc-cn#398]
英文原文为：
“ anyenum is treated exactly the same as anyelement, but adds the additional constraint that the actual type must be an enum type.”

文档中写到：
“anyenum被当做和anyelement相同，但是增加了额外的约束要求实际类型不能是一种枚举类型。”

应当翻译为：
“anyenum被当做和anyelement相同，但是增加了额外的约束要求实际类型必须是一种枚举类型。”

**Comment by ChenHuajun** [comment]
fixed
