### ISSUE TITLE
8.1.2. scale术语翻译不统一

### ISSUE THREAD

**Issue by Fatal01** [postgres-cn/pgdoc-cn#406]
翻译文档中截取如下：
8.1.2. 任意精度数字
类型numeric可以存储非常多位的数字。我们特别建议将它用于货币金额和其它要求计算准确的数量。numeric值的计算在可能的情况下会得到准确的结果，例如加法、减法、乘法。不过，numeric类型上的算术运算比整数类型或者下一节描述的浮点数类型要慢很多。

在随后的内容里，我们使用了下述术语：一个numeric的precision（精度）是整个数中有效位的总数，也就是小数点两边的位数。numeric的scale（**刻度**）是小数部分的数字位数，也就是小数点右边的部分。因此数字 23.5141 的精度为6而**刻度**为4。可以认为整数的**刻度**为零。

numeric列的最大精度和最大**比例**都是可以配置的。要声明一个类型为numeric的列

创建一个列时不使用精度或**比例**，则该列可以存储任何精度和**比例**的数字值，并且值的范围最多可以到实现精度的上限。一个这种列将不会把输入值转化成任何特定的**比例**，而带有比例声明的numeric列将把输入值转化为该**比例**（SQL标准要求缺省的比例是 0，即转化成整数精度。我们觉得这样做有点没用。如果你关心移植性，那你最好总是显式声明精度和**比例**）。

**其中scale开始翻译为刻度，但后续段落翻译为比例。**

**Comment by ChenHuajun** [comment]
刻度和比例的翻译都无法准确表达其含义，统一成“小数位数”。

**Comment by ChenHuajun** [comment]
fixed by #416
