### ISSUE TITLE
pg version 14第20.8.4章节和F.14章节脚本异常反馈

### ISSUE THREAD

**Issue by xiaoxiaoyulyw** [postgres-cn/pgdoc-cn#408]
pg version： 14

以下两个地方有误：

20.8.4. 使用 CSV 格式的日志输出
CREATE TABLE postgres_log脚本少了leader_pid integer,  query_id bigint这两个字段

F.14. file_fdw
例 F.1. 为 PostgreSQL CSV 日志创建一个外部表
CREATE FOREIGN TABLE pglog脚本少了leader_pid integer,  query_id bigint这两个字段

**Comment by ChenHuajun** [comment]
pg 14还没翻译完
