### ISSUE TITLE
“4.2.14. 表达式计算规则”一节最后一句的翻译

### ISSUE THREAD

**Issue by Bumanji** [postgres-cn/pgdoc-cn#93]
最后一句：“代替的， 在第一个位置使用WHERE或FILTER 子句阻止有问题的输入行到达聚合函数。”
原文是” Instead, use a WHERE or FILTER clause to prevent problematic input rows from reaching an aggregate function in the first place.“
原文中”in the first place“意思貌似应为”首先“，而不是”在第一个位置“。

**Comment by ChenHuajun** [comment]
非常感谢，已修正！
