### ISSUE TITLE
”4.3.3. 使用混合表示法“一节中的翻译

### ISSUE THREAD

**Issue by Bumanji** [postgres-cn/pgdoc-cn#94]
”在上面的查询中，参数a和uppercase是用位置声明的，而 uppercase是用名称声明的。“
原文：”In the above query, the arguments a and b are specified positionally, while uppercase is specified by name. “
所以翻译应该为“在上面的查询中，参数a和b是用位置声明的……”？

**Comment by ChenHuajun** [comment]
非常感谢，已修正！
