### ISSUE TITLE
“5.7.5. 系统表模式”一节中的翻译

### ISSUE THREAD

**Issue by Bumanji** [postgres-cn/pgdoc-cn#95]
“自从系统表名以pg_开头开始，最好避免使用这样的名字……“
原文：Since system table names begin with pg_, it is best to avoid such names to ensure that ……
这里的Since似乎应该翻译为”因为“？

**Comment by ChenHuajun** [comment]
Thanks！已修正！ 方便的话，可以通过提交PR修改（可以点击web上的“纠错本页面” ）
