### ISSUE TITLE
”5.8. 继承“中的翻译

### ISSUE THREAD

**Issue by Bumanji** [postgres-cn/pgdoc-cn#96]
你也可以在表名后面写一个*显示指定包括所有后代表
原文：You can also write the table name with a trailing * to explicitly specify that ……
这里的”显示“应该是笔误，应该是”显式“

**Comment by ChenHuajun** [comment]
Thanks！已修正！ 方便的话，可以通过提交PR修改（可以点击web上的“纠错本页面” ）
